paytm.payment:
  sandbox:
    merchantId: ibHneD39887859731761
    merchantKey: Na9&LhAQDzsMgJOF
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:9090/pgresponse
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}